// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace KudesniK.EntityFramework.OrderPageExtensions.Demo.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Default : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Default));
        
        string IMigrationMetadata.Id
        {
            get { return "201403171848326_Default"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
